### ISSUE TITLE
Cannot use react-router v3 jsnext build with rollup

### ISSUE THREAD

**Issue by chielkunkels** [ReactTraining/react-router#4277]
I'm using [rollup](https://github.com/rollup/rollup) to bundle up my application and since it supports tree-shaking ES6 modules I am trying to use the `jsnext:main` files of libraries as much as possible.

However, when adding react-router to my application it does with the error:

```
'PropTypes' is not exported by node_modules/react/react.js (imported by node_modules/react-router/es/InternalPropTypes.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
Error: 'PropTypes' is not exported by node_modules/react/react.js (imported by node_modules/react-router/es/InternalPropTypes.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
    at error (/Users/chiel/dev/rollup-boilerplate/node_modules/rollup/src/utils/error.js:2:14)
    at Module.trace (/Users/chiel/dev/rollup-boilerplate/node_modules/rollup/src/Module.js:364:4)
    at ModuleScope.findDeclaration (/Users/chiel/dev/rollup-boilerplate/node_modules/rollup/src/ast/scopes/ModuleScope.js:47:22)
    at MemberExpression.bind (/Users/chiel/dev/rollup-boilerplate/node_modules/rollup/src/ast/nodes/MemberExpression.js:28:28)
    at /Users/chiel/dev/rollup-boilerplate/node_modules/rollup/src/ast/Node.js:6:34
    at VariableDeclarator.eachChild (/Users/chiel/dev/rollup-boilerplate/node_modules/rollup/src/ast/Node.js:21:5)
    at VariableDeclarator.bind (/Users/chiel/dev/rollup-boilerplate/node_modules/rollup/src/ast/Node.js:6:8)
    at /Users/chiel/dev/rollup-boilerplate/node_modules/rollup/src/ast/Node.js:6:34
    at VariableDeclaration.eachChild (/Users/chiel/dev/rollup-boilerplate/node_modules/rollup/src/ast/Node.js:18:20)
    at VariableDeclaration.bind (/Users/chiel/dev/rollup-boilerplate/node_modules/rollup/src/ast/Node.js:6:8)
```

This makes sense since `'react'` is not actually an ES2015 module, it just exports an object with a `PropTypes` key. Since babel will just destructure `PropTypes` out of the exported object this will work fine with other bundlers, but not those with tree-shaking support since they're being told to interpret ES2015 modules which are not actually ES2015 modules.

Is there any chance we can change this to something like below instead:

```
import React from 'react'

const { func, object, arrayOf, oneOfType, element, shape, string } = React.PropTypes
```

Until such a time that the React library itself actually exports an ES2015 modules build? I am happy to contribute a pull request for this.

**Comment by timdorr** [comment]
This can be worked around: https://github.com/rollup/rollup/issues/855#issuecomment-240482783

A PR is probably the best way to track this. I'll close this issue out (since there is a workaround), but please do get that PR together so we can fix this without you having to do anything in your config.

**Comment by chielkunkels** [comment]
Alright sounds good, I'll get a pull request together in the coming day or so!
