### ISSUE TITLE
v4 - Object.assign - failing test

### ISSUE THREAD

**Issue by gpltaylor** [ReactTraining/react-router#4373]
## Version
4.0.0

## Test Case
IE 10.0.0 (Windows 8 0.0.0) withRouter circumvents sCU blocks FAILED
	TypeError: Object doesn't support property or method 'assign'
	   at componentWillReceiveProps (/home/travis/build/ReactTraining/react-router/packages/react-router/tests.webpack.js:26441:6 <- webpack:///modules/Core.js:141:4

## Steps to reproduce
Build in travis

## Expected Behavior
Run tests

## Actual Behavior
Fails with errors: IE 10.0.0 (Windows 8 0.0.0) withRouter circumvents sCU blocks FAILED
	TypeError: Object doesn't support property or method 'assign'
	   at componentWillReceiveProps (/home/travis/build/ReactTraining/react-router/packages/react-router/tests.webpack.js:26441:6 <- webpack:///modules/Core.js:141:4

## Extra Details
Webpack requires a polyfill for Object.assign as this is not supported in IE.

**Comment by mjackson** [comment]
Good catch. Let's use https://babeljs.io/docs/plugins/transform-object-assign/ as @pshrmn suggested in https://github.com/ReactTraining/react-router/commit/914956ee82574862c0f52e59b1409b8c839fa86f#commitcomment-20634108
