### ISSUE TITLE
TypeError: Cannot read property 'pathname' of null

### ISSUE THREAD

**Issue by evserykh** [ReactTraining/react-router#4383]
Actual for react-router@4.0.0-alpha.6

I'm trying to use `ServerRouter` component as described in example ([https://react-router.now.sh/ServerRouter](https://react-router.now.sh/ServerRouter)) and getting the error. Without SSR all works fine.

Here is stacktrace:
```
TypeError: Cannot read property 'pathname' of null
    at isActive (/react-app/node_modules/react-router/Link.js:120:46)
    at Object.children (/react-app/node_modules/react-router/Link.js:80:24)
    at Subscriber.render (/react-app/node_modules/react-broadcast/Subscriber.js:65:23)
    at /react-app/build/app.js:18:2455
    at s (/react-app/build/app.js:17:22003)
    at x._renderValidatedComponentWithoutOwnerOrContext (/react-app/build/app.js:18:2433)
    at x._renderValidatedComponent (/react-app/build/app.js:18:2741)
    at x.performInitialMount (/react-app/build/app.js:17:28173)
    at x.mountComponent (/react-app/build/app.js:17:26586)
    at Object.s.mountComponent (/react-app/build/app.js:1:27885)

```

**Comment by mjackson** [comment]
The v4 branch has changed significantly over the past few weeks. We're going to push a beta this week. Please try that instead.
