### ISSUE TITLE
Incorrectly escaped character in url will cause uncaught URIError

### ISSUE THREAD

**Issue by mwlpeeters** [ReactTraining/react-router#4495]
## Version
3.0.2

## Test Case
Any react app using react-router, simply add /% to the URL.

## Simular like
https://github.com/ReactTraining/react-router/issues/1121
But in this case it is happening without using hashlocation.

## Steps to reproduce
Add /% to any url using react-router

## Expected Behavior
A redirect to the &lt;Route path='*' component={...} /&gt;
or
an error on the onError of the Router

## Actual Behavior
Uncatchable error with the following stacktrace:
URIError: Failed to decode param '/%'
   at decodeURIComponent (native)
   at decode_param (E:\...\node_modules\express\lib\router\layer.js:167:12)
   at Layer.match (E:\...\node_modules\express\lib\router\layer.js:143:15)
   at matchLayer (E:\...\node_modules\express\lib\router\index.js:557:18)
   at next (E:\...\node_modules\express\lib\router\index.js:216:15)
   at compression (E:\...\node_modules\compression\index.js:219:5)
   at Layer.handle [as handle_request] (E:\...\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (E:\...\node_modules\express\lib\router\index.js:312:13)
   at E:\...\node_modules\express\lib\router\index.js:280:7
   at Function.process_params (E:\...\node_modules\express\lib\router\index.js:330:12)
   at next (E:\...\node_modules\express\lib\router\index.js:271:10)
   at expressInit (E:\...\node_modules\express\lib\middleware\init.js:33:5)
   at Layer.handle [as handle_request] (E:\...\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (E:\...\node_modules\express\lib\router\index.js:312:13)
   at E:\...\node_modules\express\lib\router\index.js:280:7
   at Function.process_params (E:\...\node_modules\express\lib\router\index.js:330:12)

**Comment by timdorr** [comment]
The error you're getting is tracing back to express, not this library.
