### ISSUE TITLE
React router redux, compile error

### ISSUE THREAD

**Issue by Venryx** [ReactTraining/react-router#4723]
## Version
5.0.0-alpha.2, of the subproject react-router-redux.

## Steps to reproduce
1) Set up a project with yoeman-react-firebase. (I haven't verified that this is sufficient to reproduce the error. But I did start my project with this, and suspect it's a compiler setup issue rather than a project specific one -- in which case it would most likely be sourced in the yoeman start config, as I didn't change it much.)
2) Run `npm install --save-dev react-router-redex@5.0.0-alpha.2`.
3) Run `npm run dev`, to start compiling.

## Expected Behavior
The code will compile.

## Actual Behavior
I get the following error:
```
Error: Module not found: Error: Cannot resolve 'file' or 'directory' ./actions in [root]\node_modules\react-router-redux,Module not found: Error: Cannot resolve 'file' or 'directory' ./middleware in [root]\node_modules\react-router-redux
    at Compiler.<anonymous> ([root]\build\webpack.config.js:68:11)
    at Compiler.applyPlugins ([root]\node_modules\tapable\lib\Tapable.js:26:37)
    at Watching._done ([root]\node_modules\webpack\lib\Compiler.js:78:17)
    at Watching.<anonymous> ([root]\node_modules\webpack\lib\Compiler.js:51:17)
    at [root]\node_modules\webpack\lib\Compiler.js:403:12
    at Compiler.next ([root]\node_modules\tapable\lib\Tapable.js:67:11)
    at Compiler.<anonymous> ([root]\node_modules\ts-loader\dist\after-compile.js:25:9)
    at Compiler.next ([root]\node_modules\tapable\lib\Tapable.js:69:14)
    at Compiler.<anonymous> ([root]\node_modules\webpack\lib\CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync ([root]\node_modules\tapable\lib\Tapable.js:71:13)
    at Compiler.<anonymous> ([root]\node_modules\webpack\lib\Compiler.js:400:9)
    at Compilation.<anonymous> ([root]\node_modules\webpack\lib\Compilation.js:577:13)
    at Compilation.applyPluginsAsync ([root]\node_modules\tapable\lib\Tapable.js:60:69)
    at Compilation.<anonymous> ([root]\node_modules\webpack\lib\Compilation.js:572:10)
    at Compilation.applyPluginsAsync ([root]\node_modules\tapable\lib\Tapable.js:60:69)
    at Compilation.<anonymous> ([root]\node_modules\webpack\lib\Compilation.js:567:9)
```

I looked at the react-router-redux index.js file, and noticed that it has a `require("./actions")` line. Which is odd, since there is no actions.js file in that directory.

It couldn't be that simple of an error, though?

(It's on npm, for goodness sake! They make sure there's never errors there, _right_?)

**Comment by wyze** [comment]
Duplicate of #4715.

**Comment by Venryx** [comment]
Indeed, the PR referenced (https://github.com/ReactTraining/react-router/pull/4709) seems to fix it.
