### ISSUE TITLE
Is NavLink deprecated?

### ISSUE THREAD

**Issue by jdmswong** [ReactTraining/react-router#4731]
I tried to use NavItem as described in the [docs](https://reacttraining.com/react-router/web/api/NavLink)

```
import { NavLink } from 'react-router-dom';
....
          <NavLink to="/movies">
            FILMS
          </NavLink>
```

, but received the error:
```
[1] Warning: Failed context type: The context `router.history` is marked as required in `Route`, but its value is `undefined`.
[1]     in Route (created by NavLink)
[1]     in NavLink (created by HeaderBar)
[1]     in li (created by HeaderBar)
[1]     in ul (created by HeaderBar)
[1]     in div (created by NavbarCollapse)
[1]     in Transition (created by Collapse)
[1]     in Collapse (created by NavbarCollapse)
[1]     in NavbarCollapse (created by HeaderBar)
[1]     in div (created by Grid)
[1]     in Grid (created by Navbar)
[1]     in nav (created by Navbar)
[1]     in Navbar (created by Uncontrolled(Navbar))
[1]     in Uncontrolled(Navbar) (created by HeaderBar)
[1]     in div (created by HeaderBar)
[1]     in HeaderBar (created by Connect(HeaderBar))
[1]     in Connect(HeaderBar) (created by App)
[1]     in div (created by App)
[1]     in MuiThemeProvider (created by App)
[1]     in App (created by Connect(App))
[1]     in Connect(App) (created by RouterContext)
[1]     in RouterContext
[1]     in IntlProvider (created by Connect(IntlProvider))
[1]     in Connect(IntlProvider)
[1]     in Provider
[1] /.../project/node_modules/react-transform-catch-errors/lib/index.js:47
[1]             throw err;
[1]             ^
[1] 
[1] TypeError: Cannot read property 'location' of undefined
[1]     at Route.computeMatch (/.../project/node_modules/react-router-dom/node_modules/react-router/Route.js:70:38)
[1]     at new Route (/.../project/node_modules/react-router-dom/node_modules/react-router/Route.js:43:20)
[1]     at /.../project/node_modules/react-dom/lib/ReactCompositeComponent.js:295:18
[1]     at measureLifeCyclePerf (/.../project/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
[1]     at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/.../project/node_modules/react-dom/lib/ReactCompositeComponent.js:294:16)
[1]     at ReactCompositeComponentWrapper._constructComponent (/.../project/node_modules/react-dom/lib/ReactCompositeComponent.js:280:21)
[1]     at ReactCompositeComponentWrapper.mountComponent (/.../project/node_modules/react-dom/lib/ReactCompositeComponent.js:188:21)
[1]     at Object.mountComponent (/.../project/node_modules/react-dom/lib/ReactReconciler.js:46:35)
[1]     at ReactCompositeComponentWrapper.performInitialMount (/.../project/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
[1]     at ReactCompositeComponentWrapper.mountComponent (/.../project/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
[0] webpack built 5df901110a753cda9511 in 10574ms
[0] webpack building...
[0] ./~/react-router-dom/index.js
[0] Module build failed: Error: ENOENT: no such file or directory, open '/.../project/node_modules/react-router-dom/index.js'
[0]     at Error (native)
[0]  @ ./src/containers/HeaderBar/HeaderBar.js 47:22-49
[0] webpack built 7f4a03a5904156522488 in 7859ms

```

Furthermore I don't see NavLink included in the [v3 docs](https://github.com/ReactTraining/react-router/tree/v3/docs).  How do I use this component?

**Comment by wyze** [comment]
Is this component wrapped in a `<Router />` somewhere in the parent components?

**Comment by timdorr** [comment]
Short answer: No

Long answer: Noooooooooooooo

Non-smart-ass Answer (sorry, couldn't resist the joke): It looks like you've mixed react-router 3.0 with react-router-dom 4.0 (`RouterContext` is in your stack trace). Ensure the react-router is updated to 4.0.0 and that should fix it.
