### ISSUE TITLE
react-router-redux's push gives Uncaught Error: Reducers may not dispatch actions.

### ISSUE THREAD

**Issue by stanleynguyen** [ReactTraining/react-router#5112]
Version: 4.0

I got this error when trying to use `store.dispatch(push('/'))`

```
Uncaught Error: Reducers may not dispatch actions.
    at Object.dispatch (eval at <anonymous> (http://localhost:8080/dist/bundle.js:1517:1), <anonymous>:166:13)
    at dispatch (<anonymous>:2:31875)
    at eval (eval at <anonymous> (http://localhost:8080/dist/bundle.js:1619:1), <anonymous>:14:74)
    at Object.eval [as dispatch] (eval at <anonymous> (http://localhost:8080/dist/bundle.js:2498:1), <anonymous>:15:18)
    at Object.dispatch (<anonymous>:2:1620)
    at ConnectedRouter._this.handleLocationChange (eval at <anonymous> (http://localhost:8080/dist/bundle.js:2491:1), <anonymous>:32:19)
    at listener (eval at <anonymous> (http://localhost:8080/dist/bundle.js:1028:1), <anonymous>:54:24)
    at eval (eval at <anonymous> (http://localhost:8080/dist/bundle.js:1028:1), <anonymous>:73:23)
    at Array.forEach (native)
    at Object.notifyListeners (eval at <anonymous> (http://localhost:8080/dist/bundle.js:1028:1), <anonymous>:72:15)
    at setState (eval at <anonymous> (http://localhost:8080/dist/bundle.js:1217:1), <anonymous>:96:23)
    at eval (eval at <anonymous> (http://localhost:8080/dist/bundle.js:1217:1), <anonymous>:187:11)
    at Object.confirmTransitionTo (eval at <anonymous> (http://localhost:8080/dist/bundle.js:1028:1), <anonymous>:44:7)
    at Object.push (eval at <anonymous> (http://localhost:8080/dist/bundle.js:1217:1), <anonymous>:167:23)
    at Object.eval [as dispatch] (eval at <anonymous> (http://localhost:8080/dist/bundle.js:2498:1), <anonymous>:22:25)
    at Object.dispatch (<anonymous>:2:1620)
    at token (eval at <anonymous> (http://localhost:8080/dist/bundle.js:1626:1), <anonymous>:35:23)
    at combination (eval at <anonymous> (http://localhost:8080/dist/bundle.js:2664:1), <anonymous>:123:29)
    at computeNextEntry (<anonymous>:2:27469)
    at recomputeStates (<anonymous>:2:27769)
    at <anonymous>:2:31382
    at Object.dispatch (eval at <anonymous> (http://localhost:8080/dist/bundle.js:1517:1), <anonymous>:171:22)
    at dispatch (<anonymous>:2:31875)
    at eval (eval at <anonymous> (http://localhost:8080/dist/bundle.js:1619:1), <anonymous>:14:74)
    at Object.eval [as dispatch] (eval at <anonymous> (http://localhost:8080/dist/bundle.js:2498:1), <anonymous>:15:18)
    at dispatch (<anonymous>:2:1620)
    at eval (eval at <anonymous> (http://localhost:8080/dist/bundle.js:2657:1), <anonymous>:4:12)
    at Object.ReactErrorUtils.invokeGuardedCallback (eval at <anonymous> (http://localhost:8080/dist/bundle.js:1084:1), <anonymous>:69:16)
    at executeDispatch (eval at <anonymous> (http://localhost:8080/dist/bundle.js:1056:1), <anonymous>:85:21)
    at Object.executeDispatchesInOrder (eval at <anonymous> (http://localhost:8080/dist/bundle.js:1056:1), <anonymous>:108:5)
    at executeDispatchesAndRelease (eval at <anonymous> (http://localhost:8080/dist/bundle.js:896:1), <anonymous>:43:22)
    at executeDispatchesAndReleaseTopLevel (eval at <anonymous> (http://localhost:8080/dist/bundle.js:896:1), <anonymous>:54:10)
    at Array.forEach (native)
    at forEachAccumulated (eval at <anonymous> (http://localhost:8080/dist/bundle.js:1363:1), <anonymous>:24:9)
    at Object.processEventQueue (eval at <anonymous> (http://localhost:8080/dist/bundle.js:896:1), <anonymous>:257:7)
    at runEventQueueInBatch (eval at <anonymous> (http://localhost:8080/dist/bundle.js:2078:1), <anonymous>:17:18)
    at Object.handleTopLevel [as _handleTopLevel] (eval at <anonymous> (http://localhost:8080/dist/bundle.js:2078:1), <anonymous>:28:5)
    at handleTopLevelImpl (eval at <anonymous> (http://localhost:8080/dist/bundle.js:2085:1), <anonymous>:72:24)
    at ReactDefaultBatchingStrategyTransaction.perform (eval at <anonymous> (http://localhost:8080/dist/bundle.js:951:1), <anonymous>:140:20)
    at Object.batchedUpdates (eval at <anonymous> (http://localhost:8080/dist/bundle.js:2057:1), <anonymous>:62:26)
    at Object.batchedUpdates (eval at <anonymous> (http://localhost:8080/dist/bundle.js:798:1), <anonymous>:97:27)
    at dispatchEvent (eval at <anonymous> (http://localhost:8080/dist/bundle.js:2085:1), <anonymous>:147:20)
```

**Comment by stanleynguyen** [comment]
So the cause was that I was trying to dispatch from inside another reducer and got nothing to do with react-router-redux
