### ISSUE TITLE
Cannot find module 'react-router/matchPath' when using react-router-config

### ISSUE THREAD

**Issue by iyobo** [ReactTraining/react-router#6044]
## Version
react-router: v4.2.0 || react-router-dom: v4.2.2
react-router-config: v1 beta 4

I'm attempting to use react-router-config in a server-side-rendering setup 
## Steps to reproduce
```
// In server
var RouterConfig = require('react-router-config');
```
## Expected Behavior
I should be able to require/import the module.

## Actual Behavior
```
Error: Cannot find module 'react-router/matchPath
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/iyobo/projects/kindly-api-up/node_modules/react-router-config/matchRoutes.js:5:18)
    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/iyobo/projects/kindly-api-up/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/iyobo/projects/kindly-api-up/node_modules/react-router-config/index.js:6:21)
    at Module._compile (module.js:635:30)```

**Comment by timdorr** [comment]
Something is up with your build tooling. It's definitely there: https://unpkg.com/react-router@4.2.0/matchPath.js

**Comment by iyobo** [comment]
@timdorr No build tooling used on the server.
We don't intend to use webpack on the server and have had no issues just using React.createElement in place of JSX on the server....at least in Router 3.

**Comment by pshrmn** [comment]
This might be a silly question, but are you certain that `react-router` is installed? It isn't a dependency of `react-router-config`, so you would have to install it yourself.
