### ISSUE TITLE
npm run build command fails on ppc64le

### ISSUE THREAD

**Issue by seth-priya** [ReactTraining/react-router#6108]
## Version
master

## Test Case
Trying to build on ppc64le using node version 9.11.1. 

## Steps to reproduce
git clone https://github.com/ReactTraining/react-router
cd react-router
npm install
npm run build 
npm test

## Expected Behavior
npm run build should succeed without errors

## Actual Behavior
Errors are seen all though npm test later succeeds. Last few lines of the npm run build logs
erna ERR! execute   stderr: 'npm ERR! code ELIFECYCLE\nnpm ERR! errno 2\nnpm ERR! react-router-website@ build: `NODE_ENV=production webpack -p`\nnpm ERR! Exit status 2\nnpm ERR! \nnpm ERR! Failed at the react-router-website@ build script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/test1/.npm/_logs/2018-04-25T10_54_35_325Z-debug.log\n',
lerna ERR! execute   failed: true,
lerna ERR! execute   signal: null,
lerna ERR! execute   cmd: 'npm run build',
lerna ERR! execute   timedOut: false }
child_process.js:615
    throw err;
    ^

Error: Command failed: lerna run build --stream
    at checkExecSyncError (child_process.js:575:11)
    at execSync (child_process.js:612:13)
    at exec (/home/test1/react-router/scripts/build.js:4:3)
    at Object.<anonymous> (/home/test1/react-router/scripts/build.js:12:3)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-router-packages@ build: `node ./scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-router-packages@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Any pointers would be of great help, thanks!

Regards,
Priya

**Comment by timdorr** [comment]
Looks like something with Lerna? None of us have a ppc system, as far as I know, so you're on your own here unfortunately.
