### ISSUE TITLE
react-router-dom/NavLink.js: Line 48: Invalid regular expression

### ISSUE THREAD

**Issue by dschinkel** [ReactTraining/react-router#6522]
**I'm using**:
```
    "react-router": "^4.2.0",
    "react-router-dom": "^4.1.1",
```
Node: 10.11.0
npm: 6.4.1

I'm all of a sudden getting this when I try to bundle my code, I haven't changed anything so no idea w hy:

```
events.js:167
      throw er; // Unhandled 'error' event
      ^
Error: Parsing file /node_modules/react-router-dom/NavLink.js: Line 48: Invalid regular expression
    at Deps.parseDeps (/node_modules/gulp-browserify/node_modules/module-deps/index.js:339:28)
    at /node_modules/gulp-browserify/node_modules/module-deps/index.js:282:29
    at ConcatStream.<anonymous> (/node_modules/gulp-browserify/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (events.js:187:15)
    at ConcatStream.EventEmitter.emit (domain.js:442:20)
    at finishMaybe (/node_modules/gulp-browserify/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at endWritable (/node_modules/gulp-browserify/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at ConcatStream.Writable.end (/node_modules/gulp-browserify/node_modules/readable-stream/lib/_stream_writable.js:436:5)
    at DuplexWrapper.onend (/node_modules/gulp-browserify/node_modules/readable-stream/lib/_stream_readable.js:537:10)
    at Object.onceWrapper (events.js:273:13)
Emitted 'error' event at:
    at Transform.onerror (/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at Transform.emit (events.js:182:13)
    at Transform.EventEmitter.emit (domain.js:442:20)
    at Stream.<anonymous> (/node_modules/gulp-browserify/index.js:123:14)
    at Stream.<anonymous> (/node_modules/gulp-browserify/node_modules/browserify/index.js:344:22)
    at Stream.emit (events.js:187:15)
    at Stream.EventEmitter.emit (domain.js:442:20)
    at Transform.emit (events.js:187:15)
    at Transform.EventEmitter.emit (domain.js:442:20)
    at Deps.emit (events.js:182:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by timdorr** [comment]
You have mismatched react-router and react-router-dom versions. They must be the exact same version to work together.

**Comment by dschinkel** [comment]
Does not matter I tried making them the same, still the same error. And those two versions even though diff have always worked up till this point as well.
