### ISSUE TITLE
TypeError: Cannot create property '__react_router_build__' on boolean 'true'

### ISSUE THREAD

**Issue by ethanneff** [ReactTraining/react-router#6632]
## Error

```
 FAIL  src/__tests__/index.tsx
  ● Test suite failed to run

    TypeError: Cannot create property '__react_router_build__' on boolean 'true'

      at Object.<anonymous> (node_modules/react-router/cjs/react-router.js:758:17)
      at Object.<anonymous> (node_modules/react-router/index.js:6:20)
      at Object.<anonymous> (node_modules/react-router-native/main.js:1:829)
```

## Situation

Running jest on typecript files after updating react-router dependencies.

```
import * as React from "react";
import { create } from "react-test-renderer";
import { Launcher } from "..";

describe("Launcher Container", () => {
  it("renders correctly", () => {
    const component = create(<Launcher />).toJSON();
    expect(component).toMatchSnapshot();
  });
});
```

```
 react-router-dom      4.3.1  →   4.4.0 
 react-router-native   4.3.0  →   4.4.0 
```

**Comment by pshrmn** [comment]
The line that is causing the error is

```js
global[key] = "cjs";
```
which would imply that `global` is a boolean in your tests. Can you check if you are doing that somewhere? `global` should be an object.

**Comment by mjackson** [comment]
That code only runs `if (typeof window !== "undefined")`, so it's only supposed to run in browsers, and we actually define a local `global` constant, so it shouldn't be a boolean.

**Comment by ethanneff** [comment]
Thank you for the comments. You lead me to a solution to the problem. The following is my jest config within my `package.json`. This change removed the `TypeError: Cannot create property '__react_router_build__' on boolean 'true'` error.

```diff
  "jest": {
    "preset": "react-native",
    "transform": {
      "^.+\\.(jsx?)$": "<rootDir>/node_modules/react-native/jest/preprocessor.js",
      "^.+\\.tsx?$": "ts-jest"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!react-native)/"
    ],
    "globals": {
-     "window": true,
+     "window": {},
      "ts-jest": {
        "tsConfig": "./tsconfig.jest.json"
      }
    }
  },
```


Feel free to close this issue.

Thanks!

**Comment by mjackson** [comment]
Thanks for digging deeper, @ethanneff. Glad you were able to figure it out! 😄
