### ISSUE TITLE
Examples pages on the website don't load

### ISSUE THREAD

**Issue by balajivenkatesh** [ReactTraining/react-router#6920]
## Version
Main website, Examples pages.

## Steps to reproduce
Going to https://reacttraining.com/react-router/web/example/basic or https://reacttraining.com/react-router/web/example/url-params and others under Web don't load.

On Google Chrome.

## Actual Behavior
I can see some errors in the browser console. 

Can provide more info about browser versions or the console errors if needed.

**Comment by timdorr** [comment]
Can you please copy over the errors? There's not much we can do without that info.

**Comment by balajivenkatesh** [comment]
Those pages load on Safari.

Broken on Google Chrome. This might be the most relevant one.
```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object../src/app/componentConnectors.ts (https://codesandbox.io/static/js/default~app~embed.39c0898d.chunk.js:276:10873)
    at s (https://codesandbox.io/static/js/embed.dbfd797c.js:1:571)
    at Object../src/app/components/CodeEditor/index.tsx (https://codesandbox.io/static/js/default~app~embed.39c0898d.chunk.js:276:39056)
    at s (https://codesandbox.io/static/js/embed.dbfd797c.js:1:571)
    at Object.<anonymous> (https://codesandbox.io/static/js/embed.dbfd797c.js:1:10309)
    at Object../src/embed/components/Content/index.tsx (https://codesandbox.io/static/js/embed.dbfd797c.js:1:19636)
    at s (https://codesandbox.io/static/js/embed.dbfd797c.js:1:571)
    at Module../src/embed/index.js (https://codesandbox.io/static/js/embed.dbfd797c.js:1:33125)
    at s (https://codesandbox.io/static/js/embed.dbfd797c.js:1:571)
    at Object.6 (https://codesandbox.io/static/js/embed.dbfd797c.js:1:47070
```

Other errors:
```Failed to load resource: the server responded with a status of 404 ()```
```
Error while trying to use the following icon from the Manifest: https://reacttraining.com/android-chrome-144x144.png (Download error or resource isn't a valid image)
```

**Comment by ckocheta** [comment]
I'm using Chrome(latest stable build) on Mac and everything is loading perfectly, especially i checked the 2 urls you mentioned above.

**Comment by pshrmn** [comment]
My guess is that you have the privacy badger extension installed, which is blocking code sandbox. Either disable that for the site or whitelist the code sandbox domains and the example should work.
