### ISSUE TITLE
Can't build docs locally

### ISSUE THREAD

**Issue by dkorduban** [ReactTraining/react-router#7030]
I'm trying to run docs website locally. After

```
git clone https://github.com/ReactTraining/react-router.git
cd react-router/website
yarn
yarn start
```
I get this:
```
Macintosh:website dkorduban$ yarn start
yarn run v1.19.1
$ webpack-dev-server --inline --host 0.0.0.0
ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/dkorduban/workspace/TopTal/react-router/website
ℹ ｢wds｣: 404s will fallback to /index.html
✖ ｢wdm｣: Built at: 11/14/2019 10:04:55 AM
                             Asset       Size  Chunks             Chunk Names
        android-chrome-144x144.png   4.51 KiB          [emitted]  
              apple-touch-icon.png   5.41 KiB          [emitted]  
                 browserconfig.xml  231 bytes          [emitted]  
    bundle-3ed8fb2f6c9d0bfa63c8.js    347 KiB     app  [emitted]  app
bundle-3ed8fb2f6c9d0bfa63c8.js.map    395 KiB     app  [emitted]  app
    bundle-fca722a83a579af46144.js   1.34 MiB  vendor  [emitted]  vendor
bundle-fca722a83a579af46144.js.map   1.55 MiB  vendor  [emitted]  vendor
                 favicon-16x16.png  839 bytes          [emitted]  
                 favicon-32x32.png   1.39 KiB          [emitted]  
                       favicon.ico   14.7 KiB          [emitted]  
                        index.html   1.84 KiB          [emitted]  
                     manifest.json  263 bytes          [emitted]  
                mstile-150x150.png   2.69 KiB          [emitted]  
                  react-square.png   39.8 KiB          [emitted]  
             safari-pinned-tab.svg   1.23 KiB          [emitted]  
Entrypoint app = bundle-3ed8fb2f6c9d0bfa63c8.js bundle-3ed8fb2f6c9d0bfa63c8.js.map
Entrypoint vendor = bundle-fca722a83a579af46144.js bundle-fca722a83a579af46144.js.map
[0] multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./modules/index.js 40 bytes {app} [built]
[2] multi (webpack)-dev-server/client?http://0.0.0.0:8080 react react-dom 52 bytes {vendor} [built]
[./modules/index.js] 1.68 KiB {app} [built] [failed] [1 error]
[./node_modules/react-dom/cjs/react-dom.development.js] 903 KiB {vendor} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {vendor} [built]
[./node_modules/react/cjs/react.development.js] 72.3 KiB {vendor} [built]
[./node_modules/react/index.js] 190 bytes {vendor} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {app} {vendor} [built]
[./node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080] (webpack)-dev-server/client?http://0.0.0.0:8080 4.29 KiB {app} {vendor} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {app} {vendor} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {app} {vendor} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.85 KiB {app} {vendor} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {app} {vendor} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {app} {vendor} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {app} {vendor} [built]
    + 31 hidden modules

ERROR in ./modules/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
ReferenceError: Unknown plugin "@babel/proposal-class-properties" specified in "/Users/dkorduban/workspace/TopTal/react-router/website/modules/.babelrc" at 1, attempted to resolve relative to "/Users/dkorduban/workspace/TopTal/react-router/website/modules"
    at /Users/dkorduban/workspace/TopTal/react-router/website/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/dkorduban/workspace/TopTal/react-router/website/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/dkorduban/workspace/TopTal/react-router/website/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/dkorduban/workspace/TopTal/react-router/website/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/dkorduban/workspace/TopTal/react-router/website/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/dkorduban/workspace/TopTal/react-router/website/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/dkorduban/workspace/TopTal/react-router/website/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/dkorduban/workspace/TopTal/react-router/website/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/dkorduban/workspace/TopTal/react-router/website/node_modules/babel-loader/lib/index.js:173:20)
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  536 KiB       0  
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./index.html.ejs] 2.42 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 528 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
ℹ ｢wdm｣: Failed to compile.
```
My Node version is v12.13.0. I tried to remove yarn.lock and `yarn` again, but the problem persists.

**Comment by timdorr** [comment]
Should be fixed when #7025 lands.
