### ISSUE TITLE
Sub-routes are not respecting a BrowserRouter basename parameter.

### ISSUE THREAD

**Issue by laurencefass** [ReactTraining/react-router#7033]
## Version

**Please replace this sentence with the React Router version that you are using.**
    "react-router-dom": "^5.0.1"

## Test Case

Sub-routes are not respecting a BrowserRouter basename parameter. The basename mechanism works fine for top level routes but is extracted for level 1 sub-routes.

## Steps to reproduce

live example here: https://razzle.syntapse.co.uk/nested/topics

```
import React from 'react';
// other imports here
// ...
import {
  BrowserRouter as Router,
  Switch,
  Route,
  Link,
  useParams,
  useRouteMatch
} from "react-router-dom";

export function NestedRoutes() {
  let { path, url } = useRouteMatch();

  return (
    <Page title="Demonstration of nested routes" background="brown" color="yellow">
    <Router>
      <div className="navbar">
        <Link to={`${url}/topics`}>Topics</Link>
      </div>
      <Switch>
        <Route exact path="/" component={Home} />
        <Route path={`${url}/topics`}>
          <Topics />
        </Route>
      </Switch>
    </Router>
    </Page>
  );
}

function Topics() {
  // The `path` lets us build <Route> paths that are
  // relative to the parent route, while the `url` lets
  // us build relative links.
  let { path, url } = useRouteMatch();

  return (
    <Content title="Topics" background="yellow" color="darkgreen">
      <h2>Topics</h2>
      <p>url ={ url }, path = { path }</p>
      <p>One component is used to render multiple routes</p>
      <div className="navbar">
        <Link to={`${url}/rendering`}>Rendering</Link>
        <Link to={`${url}/components`}>Components</Link>
        <Link to={`${url}/routing`}>Routing</Link>
        <Link to={`${url}/modules`}>Modules</Link>
      </div>
      <Switch>
        <Route exact path={path}>
          <h3>Please select a topic.</h3>
        </Route>
        <Route path={`${path}/:topicId`}>
          <Topic />
        </Route>
      </Switch>
    </Content>      
  );
}

function Topic() {
  // The <Route> that rendered this component has a
  // path of `/topics/:topicId`. The `:topicId` portion
  // of the URL indicates a placeholder that we can
  // get from `useParams()`.
  let { topicId } = useParams();
  return (<>
    <h1>{topicId}</h1>
    <Article></Article>
  </>);
}

export function Article() {
  const Style = {
    width: "80%",
    margin: "0 auto"
  };
  return (<div>
    <img style={Style} src={randomImageURL()}/>
    <Lorem style={Style} count="3" seed={randomNumber()}/>
  </div>);
}

export function Page(props) {
  let { path, url } = useRouteMatch();

  return (
    <div>
      <p>url ={ url }, path = { path }</p>
      <Navbar></Navbar>
      <Content {...props}></Content>
      <Footer></Footer>
      </div>
  );
}

export class Home extends React.Component<{}, {}> {
  public render() {
    return (<>
        <Page title="Welcome to Syntapse Razzle Typescript" background="blue" color="yellow">
          <Article></Article>
        </Page>  
    </>);
  }
}

export function About() {
  return(<>
    <Page title="About Syntapse, Razzle and Typescript." background="purple" color="orange">
      <Article></Article>
    </Page>  
  </>);
}

export function Examples() {
  return(<>
    <Page title="Typescript Examples page" background="darkgreen" color="lightgray">
      <Article></Article>
    </Page> 
  </>);
}

export function Navbar(props) {
  return (<div className="navbar">
    <Link to="/">Home</Link>
    <Link to="/about">About</Link>
    <Link to="/examples">Examples</Link>
    <Link to="/nested">Nested</Link>
  </div>);
}

export function Footer() {
  return (
    <div className="Footer">
      <p className="Content-intro">
        To get started, edit <code>src/App.tsx</code> or{' '}
        <code>src/Home.tsx</code> and save to reload.
      </p>
      <ul className="Content-resources">
        <li>
          <a href="https://github.com/jaredpalmer/razzle">Docs</a>
        </li>
        <li>
          <a href="https://github.com/jaredpalmer/razzle/issues">Issues</a>
        </li>
        <li>
          <a href="https://palmer.chat">Community Slack</a>
        </li>
      </ul>
    </div>
  );
}

export function Content(props) {
  const headerStyle = {
    background: props.background,
    color: props.color
  };
  return (
    <div className="Content">
      <div className="Content-header" style={headerStyle}>
        <img src={logo} className="Content-logo" alt="logo" />
        <h2>{props.title}</h2>
      </div>
      <p>
        {props.children}
      </p>
    </div>
  );
}
```

## Expected Behavior

clicking Topics @ https://razzle.syntapse.co.uk/typescript-dev/nested
1. render correct parameterised Topic component and 
2. set route to https://razzle.syntapse.co.uk/typescript-dev/nested/topics

## Actual Behavior
clicking Topics @ https://razzle.syntapse.co.uk/typescript-dev/nested
1. render correct parameterised Topic component and 
2. set route to https://razzle.syntapse.co.uk/nested/topics

omitting the basename set on the BrowserRouter.

**Comment by laurencefass** [comment]
attempted workaround.

I added the basename to the nested router which provides correct routing but the back and reaload buttons are both broken and give me a white screen.

Having to add the basename to subroutes throughout the entire system feels wrong so I am guessing this is incorrect.

```
export function NestedRoutes() {
  let { path, url } = useRouteMatch();
  return (
    <Page title="Demonstration of nested routes" background="brown" color="yello">
    <Router **basename="/typescript-dev"**>
      <div className="navbar">
        <Link to={`${url}/topics`}>Topics</Link>
      </div>
      <Switch>
        <Route exact path="/" component={Home} />
        <Route path={`${url}/topics`}>
          <Topics />
        </Route>
      </Switch>
    </Router>
    </Page>
  );
}
```

**Comment by laurencefass** [comment]
Another problem with this example is that I can route to https://razzle.syntapse.co.uk/typescript-dev/nested by clicking menu item but if i reload the page i see

```
Invariant failed: Browser history needs a DOM

[0m [90m 11 | [39m  assets [33m=[39m require(process[33m.[39menv[33m.[39m[33mRAZZLE_ASSETS_MANIFEST[39m[33m![39m)[33m;[39m[0m
[0m [90m 12 | [39m}[33m;[39m[0m
[0m[31m[1m>[22m[39m[90m 13 | [39msyncLoadAssets()[33m;[39m[0m
[0m [90m 14 | [39m[0m
[0m [90m 15 | [39m[36mconst[39m server [33m=[39m express()[0m
[0m [90m 16 | [39m  [33m.[39mdisable([32m'x-powered-by'[39m)[0m

    at invariant (/app/razzle/typescript/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:13:11)
    at Object.createHistory [as createBrowserHistory] (/app/razzle/typescript/node_modules/history/cjs/history.js:273:16)
    at new BrowserRouter (/app/razzle/typescript/node_modules/react-router-dom/modules/BrowserRouter.js:11:13)
    at processChild (/app/razzle/typescript/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:14)
    at resolve (/app/razzle/typescript/node_modules/react-dom/cjs/react-dom-server.node.development.js:3126:5)
    at ReactDOMServerRenderer.render (/app/razzle/typescript/node_modules/react-dom/cjs/react-dom-server.node.development.js:3600:22)
    at ReactDOMServerRenderer.read (/app/razzle/typescript/node_modules/react-dom/cjs/react-dom-server.node.development.js:3538:29)
    at renderToString (/app/razzle/typescript/node_modules/react-dom/cjs/react-dom-server.node.development.js:4247:27)
    at module.exports../src/server.tsx.express__WEBPACK_IMPORTED_MODULE_0___default.disable.use.get (/app/razzle/typescript/src/server.tsx:13:1)
    at Layer.handle [as handle_request] (/app/razzle/typescript/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by laurencefass** [comment]
i need 5.1+ for this
