### ISSUE TITLE
Example is broken for Brave browser

### ISSUE THREAD

**Issue by arminghm** [ReactTraining/react-router#7101]
The [Redirects (Auth)](https://reacttraining.com/react-router/web/example/auth-workflow) example is broken for Brave browser

This is the error printer in console

```
Error while trying to use the following icon from the Manifest: https://reacttraining.com/android-chrome-144x144.png (Download error or resource isn't a valid image)
utils.js:78 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.../common/lib/utils/analytics/utils.js (https://codesandbox.io/static/js/default~app~embed.e99ea9f8a.chunk.js:474:92638)
    at s (https://codesandbox.io/static/js/embed.3380f1fe6.js:1:571)
    at Object.../common/lib/utils/analytics/amplitude.js (https://codesandbox.io/static/js/default~app~embed.e99ea9f8a.chunk.js:474:81525)
    at s (https://codesandbox.io/static/js/embed.3380f1fe6.js:1:571)
    at Object.../common/lib/utils/analytics/index.js (https://codesandbox.io/static/js/default~app~embed.e99ea9f8a.chunk.js:474:85666)
    at s (https://codesandbox.io/static/js/embed.3380f1fe6.js:1:571)
    at Module../src/embed/index.js (https://codesandbox.io/static/js/embed.3380f1fe6.js:27:62782)
    at s (https://codesandbox.io/static/js/embed.3380f1fe6.js:1:571)
    at Object.6 (https://codesandbox.io/static/js/embed.3380f1fe6.js:27:84331)
    at s (https://codesandbox.io/static/js/embed.3380f1fe6.js:1:571)
```

**Comment by arminghm** [comment]
oh the cookies fro codesandbox.io was blocked
