### ISSUE TITLE
Using <Link> within <StaticRouter> results in error thrown at runtime

### ISSUE THREAD

**Issue by danpantry** [ReactTraining/react-router#7124]
## Version

**6.0.0-alpha.1**

## Test Case

https://codesandbox.io/s/react-router-38xq6

## Steps to reproduce

Attempt to use a `<Link />` inside of a `<StaticRouter />`.

## Expected Behavior

The link is rendered as an `<a>`.

## Actual Behavior

A runtime error with the following text is thrown:

```
TypeError: b.createHref is not a function

      at Object.useHref (packages/react-router/modules/index.js:363:10)
      at packages/react-router-dom/modules/index.js:137:14
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:15108:18)
      at updateForwardRef (node_modules/react-dom/cjs/react-dom.development.js:16746:20)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:18522:16)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:347:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:397:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:454:31)
      at beginWork$$1 (node_modules/react-dom/cjs/react-dom.development.js:23217:7)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22211:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22185:22)
      at renderRoot (node_modules/react-dom/cjs/react-dom.development.js:21878:11)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21419:22)
      at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:24319:3)
      at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:24347:10)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:24436:10)
      at node_modules/react-dom/cjs/react-dom.development.js:24963:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:21687:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:24962:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:25042:12)
      at node_modules/@testing-library/react/dist/index.js:86:25
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:21643:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1002:14)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1418:12)
      at render (node_modules/@testing-library/react/dist/index.js:82:26)
```

I use `<StaticRouter />` in tests. I can use `<MemoryRouter />` in tests (which does resolve this issue), but this potentially bricks server side rendering.

**Comment by MeiKatz** [comment]
Currently I have no time for a PR, but if you @danpantry would like to do it, it should only be something like this:
```js
createHref(location) {
  return createPath(location);
}
```

**Comment by danpantry** [comment]
Can do
