### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by BingoStyle** [ReactTraining/react-router#7544]
build for dev branch

```
yarn
yarn build
```

get this
```
(function (exports, require, module, __filename, __dirname) { import fs from 'fs';

                                                            
SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
error Command failed with exit code 1.
```

**Comment by timdorr** [comment]
We don't provide support for the build process. You'll have to figure this out yourself.
