### ISSUE TITLE
[v6] cannot mock useNavigate 

### ISSUE THREAD

**Issue by zacharytyhacz** [ReactTraining/react-router#7828]
## Version

```json
        "react": "^16.9.0",
        "react-dom": "^16.9.0",
        "react-router": "^6.0.0-alpha.5",
        "react-router-dom": "^6.0.0-alpha.5",
```
## Test Case

https://github.com/zacharytyhacz/useNavigateBug

related stackoverflow: https://stackoverflow.com/questions/66284286/react-jest-mock-usenavigate

## Steps to reproduce
1. create a functional component that uses the `useNavigate` hook
2. create a jest test for this component and attempt to mock the `useNavigate` return value so you can test what `navigate(..)` was called with 
3. run your tests

## Expected Behavior
I should be able to at least test mock `useNavigate` like this minimally without having to wrap my component in a `<Router />` or `<BrowserRouter />` or anything. Should immediately get mocked.

## Actual Behavior
function `useNavigate` throws error when attempted to be mocked.

```
useNavigate() may be used only in the context of a <Router> component
```

Full error from jest tests:
```bash
    useNavigate() may be used only in the context of a <Router> component.

      at k (packages/react-router/index.tsx:41:6)
      at Object.W (node_modules/react-router/umd/react-router.development.js:7:25)
      at Object.<anonymous>.exports.default (Home.tsx:5:22)
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:829:32)
      at renderElement (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:643:26)
      at fn (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:707:46)
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/src/Utils.js:100:18)
      at Object.render (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:707:20)
      at new ShallowWrapper (node_modules/enzyme/src/ShallowWrapper.js:411:22)
      at Object.shallow (node_modules/enzyme/src/shallow.js:10:10)
      at Object.<anonymous> (tests/Home.test.tsx:70:25)
```

**Comment by zacharytyhacz** [comment]
I was incorrectly setting up the mocked import instead of the test, not outside of the test. Should be mocked like this:

```typescript
import React from 'react';
import { shallow, mount } from 'enzyme';
import App from './App';
...

// have my mock up here
const mockedNavigate = jest.fn();

jest.mock('react-router-dom', () => {
    const originalRouterDom = jest.requireActual('react-router-dom');
    return {
        __esModule: true,
        ...originalRouterDom,
        useNavigate: () => mockedNavigate
    };
});

describe("App.tsx", () => {
// not in here in the test
.......
...
```
